### ISSUE TITLE
Update modularadmin, unify {{ base_url() }}  and {{ public_path }}

### ISSUE THREAD

**Issue by killua-eu** [vaizard/glued#104]
- [x] Get current build of https://github.com/vaizard/glued-modular-admin
- [x] Twigs have both {{ base_url() }}  and {{ public_path }} ... I think we now use public_path?

**Comment by pohadkar** [comment]
vsechny base_path nahrazeny public_path
dashboard_new updatovan a prejmenovan na dashboard
paralelni stary dashboard smazan

**Comment by killua-eu** [comment]
Attacked with PR #106
