### ISSUE TITLE
Nicer playground separation

### ISSUE THREAD

**Issue by killua-eu** [Vaizard/glued#18]
currently locating the playground in `/glued/playground/class_name.php` doesnt really work too well. code separation fails when a playground class needs i.e. a twig template, or additional public files. I propose to change the files layout to `/playground/project_name/{classes,controllers, ...}/class_name.php` copying /glued's dir inner structure, adding also a public directory.

**Comment by kajjakoficial** [comment]
vyzkousel jsem presunout do takove struktury modul Pohadkar_platby. presunuti controller scriptu do struktury Playground\pohadkar_platby\Controllers bylo funkcni pote co jsem zmenil namespace tohoto scriptu na namespace Glued\Playground\pohadkar_platby\Controllers; ovsem presunuti twig templatu do Playground\pohadkar_platby\Views je problematicke. pokusil jsem se tam nasmerovat zaverecny render timto zapisem: '../Playground/pohadkar_platby/Views/platby.twig', ale slim hlasi chybu, Twig_Error_Loader, Looks like you try to load a template outside configured directories. twig je totiz nastaven v souboru dependencies.php tak, ze templaty musi byt pouze v root adresari Views. toto nevim jak by se dalo resit.

**Comment by pohadkar** [comment]
vyzkousel jsem presunout do takove struktury modul Pohadkar_platby. presunuti controller scriptu do struktury Playground\pohadkar_platby\Controllers bylo funkcni pote co jsem zmenil namespace tohoto scriptu na namespace Glued\Playground\pohadkar_platby\Controllers; ovsem presunuti twig templatu do Playground\pohadkar_platby\Views je problematicke. pokusil jsem se tam nasmerovat zaverecny render timto zapisem: '../Playground/pohadkar_platby/Views/platby.twig', ale slim hlasi chybu, Twig_Error_Loader, Looks like you try to load a template outside configured directories. twig je totiz nastaven v souboru dependencies.php tak, ze templaty musi byt pouze v root adresari Views. toto nevim jak by se dalo resit.

**Comment by killua-eu** [comment]
ok, for now we keep the playground as is, even tough its a pain. new stuff is to be developed in branches or somewhere, where it wont look nasty af.
