### ISSUE TITLE
t_privileges table doesnt contain ownership

### ISSUE THREAD

**Issue by killua-eu** [vaizard/glued#23]
xparpb intentionally omitted c_owner, c_group, c_unixperms, c_status from the t_privileges table. When preparing the sql dump, i noticed that it would be really helpful to somehow identify rows that are default data and should never be deleted.  add a "protected" column to all tables that expect default data. the protected column allows greater flexibility (i.e. have default / install data, and have another different layer of undeletable / hardcoded data].

**Comment by pohadkar** [comment]
do tabulky t_privileges jsem tedy pridal sloupec c_protected typu tinyint s defaultni hodnotou 0.

**Comment by killua-eu** [comment]
prima, rposim o aktualizaci https://github.com/Vaizard/glued/blob/master/extras/sqldump/slim.sql (asi nový dump ve kterem nebudou autikační data ...). Toto by chtělo speciální bash skriptík ve smyslu https://stackoverflow.com/questions/135835/limiting-the-number-of-records-from-mysqldump tak, že dumpuješ 1. strukturu všech tabulek, 2. všechna data z vybraných tabulek, 3. vybraná data (omezená where query) z jiných vybraných tabulek... Tak budeme mít verzovanou v gitu také databázi a její stav ve kterém by měla být při každé změně.
