### ISSUE TITLE
UX testing and implementation

### ISSUE THREAD

**Issue by killua-eu** [vaizard/glued#34]
Apart from bootstrap, glued has no extra styling what so ever. There are basically 4 opensource admin/dashboards bootstrap templates out there with sources on github. The most visually pleasing to me was modularcode and code looks neat enough to understand.

- http://www.blacktie.co/demo/dashgum/morris.html
- https://modularcode.io/modular-admin-html/index.html
- https://blackrockdigital.github.io/startbootstrap-sb-admin/
- https://blackrockdigital.github.io/startbootstrap-sb-admin-2/
- https://github.com/mrholek/CoreUI-Vue
- https://github.com/Daemonite/material

@pohadkar , could you please test what will happen if you put modularcore (or another template if you find out that modular sucks really bad) into glued's twigs and how will it behave with the mozilla json formgen and the rest of glued.

**NOTE** that this will require to bump bootstrap to v. 4.0.0-beta (all of the above templates are based of 4.0.0 branch of bootstrap). If this stuff works, we'll keep it and only tweak it.

**Comment by pohadkar** [comment]
tyto dashboardy vyzaduji bootstrap4. bootstrap 4 vyzaduje jquery 3.2.1.
zmenil jsem tedy nase pripojene jquery na 3.2.1 a nas bootstrap na 4.0.0-beta.
rozhodilo to nas layout, protoze zmen v bootstrapu 4 vs 3 je hodne. (jine tridy hlavne, ale i jina struktura prvku)
rychlym prepisel navigace jsem zprovoznil prihlaseni.
co nas zajimalo hlavne, byly nase generovane formulare pomoci react-jsonschema-form
po vyzkouseni stale jedou. nicmene jejich vizual byl tvore pro boostrap 3, takze ve 4 jsou nektere prvky podelane. 
kontrolou na strance vyvoje react-jsonschema-form jsem nenasel zadnou zminku, ze by byl system pro bootstrap 4 upravovan. pouzivame nejnovejsi verzi.

**Comment by killua-eu** [comment]
Ad 3: http://jsonforms.io a https://github.com/dschnelldavis/angular2-json-schema-form a http://schemaform.io/ vypadají jako vyvíjené .. nějakou podporu pro bs4 má jsonforms, ale netestoval jsem.
Ad 2: je pravda že BS4 nebude z bety ven aspoň 3 měsíce. Ale předělávat pak hromadu věcí mi přijde naprd.
Ad 1: zkusil bys prosím, zda to nějak lze? poptal jsem mezitím mailem jak generovat z mpm balíčku single static js tak jak ho potřebujem

**Comment by pohadkar** [comment]
formy nastylovany. vysledek v pull requestu  #37

**Comment by killua-eu** [comment]
Super, teď už jen chybí úpravu používat ten bs4 template... Tedy přesunout obsah menu co se týká controllers do pruhu vlevo, user akce mit pod odpovídající lištou nahoře.. Tedy vizuálně vypalovat nás obsah do layout logiky, která je v příkladu toho modularu
