### ISSUE TITLE
Contacts

### ISSUE THREAD

**Issue by killua-eu** [vaizard/glued#44]
- **kind** describes if the contact is an individual, group, organization or location. Using an anyOf subelement instead of just assigning a value makes it easier for value-based optional form elements, see https://mozilla-services.github.io/react-jsonschema-form/ - "schema dependencies" tab. Allowed elements (anyOf), with value "1" are:
  - `individual`
  - `group`
  - `organization`
  - `location`
- **n**, structured name, relevant only if `kind == "individual"`. Has subelements
  - honorific_prefix	
  - given_name
  - additional_name
  - family name
  - honorific suffix
- **fn**, short for full name,
  - if kind is `individual` then the value is concatenated "n"
  - if kind == group | organization | location then this is where its name is stored.
- **nickname**
- **adr** is the address with subelements
  - street address
  - extended address (building name, floor, room number ...)
  - locacity
  - region
  - postal code
  - post office box
  - country name
  - geo
- **email**
- **timeline**
  - type: birthday, deathday, marriage ....
  - value: datetime
  - place: not required
  - anniversary: 0/1
- **gender**
- **tel** telephone number
- **url**
- **note**
- **comm** instant messengers (facebook messangeer, icq, etc.), voip services (whatsapp, etc.)
- **bank** bank connection with subelements
  - account
  - code
  - iban
  - route
  - name
  - address
- **id** identification document or number
  - domain
  - id {doc, onin=ič, pnin = rč, vatid = dič}
- **rel** a relationship graph of this contact to other contacts
  - type: is_member_of, has_member, is_friend_of, ...
- **file** files attached to this card
  - types: logo, photo, profile_image
- **wallet** crypto wallet for diff. currencies
- **cc** credit/debit card
  - type
  - number
  - name
  - exp
  - cvv
- **roles** - contact roles (creator, editor, manager, etc.)
- **lang** - languages that can be used for communication
- **focus** 
  - type: i.e. fishing, computer science etc. 
  - kind:
    - expertise: A professional subject area that the person has knowledge of.
    - hobby: A recreational activity that the person actively engages in.
    - interest: A recreational activity that the person is interested in, but does not necessarily take part in. 
  - level: low, high, expert?

TODO: define focus economy.

---

Data according the jCard standard look like this:

```json
["vcard",
  [
    ["version", {}, "text", "4.0"],
    ["n", {}, "text", ["Gump", "Forrest", "", "Mr.", ""]],
    ["fn", {}, "text", "Forrest Gump"],
    ["org", {}, "text", "Bubba Gump Shrimp Co."],
    ["title", {} ,"text", "Shrimp Man"],
    ["photo", {"mediatype":"image/gif"}, "uri", "http://www.example.com/dir_photos/my_photo.gif"],
    ["tel", {"type":["work", "voice"]}, "uri", "tel:+1-111-555-1212"],
    ["tel", {"type":["home", "voice"]}, "uri", "tel:+1-404-555-1212"],
    ["adr",
      {"label":"100 Waters Edge\nBaytown, LA 30314\nUnited States of America", "type":"work", "pref":"1"},
      "text",
      ["", "", "100 Waters Edge", "Baytown", "LA", "30314", "United States of America"]
    ],
    ["adr",
      {"label":"42 Plantation St.\nBaytown, LA 30314\nUnited States of America", "type":"home"},
      "text",
      ["", "", "42 Plantation St.", "Baytown", "LA", "30314", "United States of America"]
    ],
    ["email", {}, "text", "forrestgump@example.com"],
    ["rev", {}, "timestamp", "2008-04-24T19:52:43Z"]
  ]
]
```

I'm not very fond of having data stored just as arrays, I find objects preferable, esp. if we want to use json-schema-react or similar libraries. If we decide to stay as close to jCard as possible, we can use a schema similar to what's in n, fn1 or fn2, or we can use something more verbose such as according to adr. 

```json{
{
"data": {
	"kind": {
		"individual": "1"
	},
	"n": [
		[{ "metadata": "vals" }, "datatype", ["$prefix", "$name", "$addname", "$famname", "$sufix"]],
		[{"type": ["work", "voice"]}, "text", ["Sir", "Dick", "Adam", "Twist", "PhD."]]
	],
	"fn1": "Sir Dick Adam Twist, PhD.",
	"fn2": [
		[{ "metadata": "value" }, "datatype", "the actual name"],
		[{"valid-from": "20180122" }, "text", "Sir Dick Adam Twist, PhD."]
	],
        "adr": [{
        	"type": ["work", "postal"],
       		"sa": "Street address",
       		"ea": "Extended address (building name, floor, room number)",
       		"lo": "Locacity (town)",
       		"re": "Region",
	        "pc": "Postal code",
       		"pb": "Post office box",
		"cn": "Country name"  
        	}
     	]
	}
}```

**Comment by pohadkar** [comment]
$ohno_type['n'] = array('m', 's', 'Structured name');   // strukturovane jmeno, spojene s formatovanym jmenem, u natural vzdy musi byt aspon 1 ! je na to vyjimka u mazani
    $ohno_type['org'] = array('s', 'b', 'Organization name');   // nazev organizace, u legal vzdy musi byt aspon 1 ! vyjimka u mazani
    $ohno_type['nickname'] = array('m', 'b', 'Nickname');   // prezdivka, muze byt vickrat, proto m
    $ohno_type['bday'] = array('s', 'b', 'Birthday');   // datum narozeni, jednou
    $ohno_type['sex'] = array('s', 'b', 'Sex');   // 0 - neurceno, 1 - muz, 2 - zena, 9 - nehraje roli
    $ohno_type['adr'] = array('m', 's', 'Address');
    $ohno_type['tel'] = array('m', 'b', 'Telephone');
    $ohno_type['email'] = array('m', 'b', 'Email');
    $ohno_type['url'] = array('m', 'b', 'Url');
    $ohno_type['impp'] = array('m', 'b', 'Instant Messenger');
    $ohno_type['x-bank'] = array('m', 's', 'Bank connection');
    $ohno_type['x-contact'] = array('m', 'b', 'Unfiled contact');
    $ohno_type['x-cc'] = array('m', 's', 'Credit card');
    $ohno_type['x-id'] = array('m', 's', 'Identification');
    $ohno_type['note'] = array('m', 'b', 'Note');   // poznamka, muze byt pro registrovaneho i sdilena, pridava se jinym zpusobem, nove bude v selectu ale bude zobrazena v pravem sloupci
    $ohno_type['file'] = array('m', 'b', 'File');   // pri vyberu v slectu se otevre popup (multi a basic)

**Comment by pohadkar** [comment]
// definice strukturovanych typu. ty uz strukturovane nebudou ale taky budou mit nazev a muzou byt single a multiple (i kdyz to nevim)
    $ohno_structured['n']['x-fn'] = array('s', 'Formated name'); // formatovany tvar toho vseho, tj zretezeni
    $ohno_structured['n']['honorific-prefix'] = array('s', 'Honorific prefix');
    $ohno_structured['n']['given-name'] = array('s', 'Given name');
    $ohno_structured['n']['additional-name'] = array('s', 'Additional name');
    $ohno_structured['n']['family-name'] = array('s', 'Family name');
    $ohno_structured['n']['honorific-suffix'] = array('s', 'Honorific suffix');

    $ohno_structured['adr']['street-address'] = array('s', 'Street');
    $ohno_structured['adr']['extended-address'] = array('s', 'Apartment number'); // napr cislo bytu
    $ohno_structured['adr']['locality'] = array('s', 'City');
    $ohno_structured['adr']['region'] = array('s', 'Region');   // kraj, nebo stat ve federaci
    $ohno_structured['adr']['postal-code'] = array('s', 'Postal code');
    $ohno_structured['adr']['post-office-box'] = array('s', 'P.O.Box');
    $ohno_structured['adr']['country-name'] = array('s', 'Country');
    $ohno_structured['adr']['x-geo'] = array('s', 'Geo');   // gps coords

    $ohno_structured['x-bank']['account'] = array('s', 'Account');
    $ohno_structured['x-bank']['code'] = array('s', 'Code');
    $ohno_structured['x-bank']['iban'] = array('s', 'Iban');
    $ohno_structured['x-bank']['route'] = array('s', 'Route');
    $ohno_structured['x-bank']['name'] = array('s', 'Name');
    $ohno_structured['x-bank']['address'] = array('s', 'Address');

    $ohno_structured['x-cc']['type'] = array('s', 'Type');
    $ohno_structured['x-cc']['number'] = array('s', 'Number');
    $ohno_structured['x-cc']['name'] = array('s', 'Name');
    $ohno_structured['x-cc']['exp'] = array('s', 'Expire');
    $ohno_structured['x-cc']['cvv'] = array('s', 'CVV');

    $ohno_structured['x-id']['domain'] = array('s', 'Domain');    // zeme, nebo jina "domena" ke ktere se id vztahuje (toto tedy bude vyplneno vzdy)
    $ohno_structured['x-id']['id'] = array('s', 'ID');  // identifikator - u firem ičo, u lidí rodné čislo (tady bude hrat roli jeste type, a to doc, onin = ič, pnin = rč nebo vatid = dič)

**Comment by killua-eu** [comment]
Díky, upraven prvni comment, nutno rozseknout který json zápis používat s ohledem na react-jsonschema-form.
