### ISSUE TITLE
Update RJSF dependency

### ISSUE THREAD

**Issue by killua-eu** [Vaizard/glued#56]
RJSF had a major release. We should bump our library to the curr version.
https://github.com/mozilla-services/react-jsonschema-form/releases/tag/v1.0.0
Also test addition of https://github.com/RxNT/react-jsonschema-form-extras and its goodies.

**Comment by pohadkar** [comment]
knihovna vymenena. byla tam knihovna https://killua.vaizard.xyz/react-jsonschema-form.js, nahradil jsem ji https://unpkg.com/react-jsonschema-form@1.0.3/dist/react-jsonschema-form.js

je celkem zahada ze jsme to brali z killua. pry to souviselo s timto pullem https://github.com/Vaizard/glued/pull/37

**Comment by pohadkar** [comment]
tak pry to predtim neslo prestylovat, kdyz to bylo pripojene z unpkg. a proto to bylo generovane na killua. ted ta nova verze uz je pripojena z unpkg a prestylovani funguje. takze zaviram

**Comment by killua-eu** [comment]
Výborně, uzavřeme s PR který ponese změnu

**Comment by killua-eu** [comment]
https://github.com/Vaizard/glued/pull/60/commits/52e57f2e6d59c3206b8da4564f3e4a8a8c9f13a3 closes this issue.
