### ISSUE TITLE
Menu items don't stay open in modularadmin

### ISSUE THREAD

**Issue by killua-eu** [vaizard/glued#61]
According to japex:

>  jen tak z hecu jsem zkusil zjistit, jak by slo nastavit, kdyz jsi v podmenu tak nadmenu zustane otevrene a aktivni, ale je s tim spojeno hodne zmen trid. to asi v tom view nedokazu vse nastavit. menu by se muselo generovat v php, kde bych ty tridy mohl snadno menit. s kazdym otevrenim souvisi 2x atribut, a 3x zmena tridy to by to template navigation vypadalo jak deravej cednik :))) kdybych to mel zpracovat jen twigem. atribut u ul a u a, na li musi byt opet a idealne i active open, a na ul musi byt trida in in a na podmenu li musi byt zase active. plugin co se o to stara se jmenuje metismenu a je zahrnut v tom dashboardu ovsem je tam enjaka starsi verze 😀

The thing works in the demo quite well (https://modularcode.io/modular-admin-html/charts-flot.html) so, the problem is probably too much deleting. So lets:

- bump modularadmin to current
- figure out why it works in the demo

**Comment by pohadkar** [comment]
ano, taky jsem koukal ze v demu to funguje. ale soucasne demo jede na vyssi verzi vseho, nez mame my. je tam tedy napriklad jquery 3.0 a jiste i vyssi verze metismenu, ktere se o to stara. s delety, ktere jsme udelali v  dashboardu to podle me nesouvisi. menu mame stejne a js mame taky stejne jako v dobe kdy jsme to instalovali.

**Comment by killua-eu** [comment]
Viz také https://github.com/vaizard/glued/issues/85

**Comment by pohadkar** [comment]
prozkoumal jsem kod dema.
na kazde postrance je menu vygenrovane znova  a jinak.
otevrena nadsekce ma
<li class="active open">
a aktivni podsekce ma 
<li class="active">
pokud se nadsekce neotevira, tak ma taky pri vybrani
<li class="active"> ve sve vyssi urovni

tyhle veci budu muset posilat jako promenne z jednotlivych controleru, ktere vypisuji obsah a sablona menu na ne bude muset reagovat.

**Comment by pohadkar** [comment]
kazdy controler ktery odpovida polozce menu ted posila do template promennou
'ui_menu_active' => 'nazev-polozky-menu'
navigace pak ma na polozkach li podminky
{% if ui_menu_active == "nazev-polozky-menu" %} class="active"{% endif %}
pokud maji polzky spolecne nadmenu
je na nem podminka s or,napr
{% if (ui_menu_active == "assets" or ui_menu_active == "consumables" or ui_menu_active == "parts") %} class="active open"{% endif %}

**Comment by pohadkar** [comment]
@killua-eu prosim uprav generovane css v dashboardu.
v app.css na radku 1849 zrus definici pozadi pro vybrane nadmenu.
![zrusit_background](https://user-images.githubusercontent.com/427799/57580715-5a05bb00-74ad-11e9-89f4-b81210833643.jpg)
