### ISSUE TITLE
Change rjsf ui schema for title/description

### ISSUE THREAD

**Issue by killua-eu** [vaizard/glued#71]
RJSF renders title and description above the form by default as `<legend>` and
`<p id="root__description" class="field-description">`. We should be able to not display the title and description at all, or render them in comments. If that's not possible, add custom css to just hide this (please check first, if this wont break something else).

**Comment by pohadkar** [comment]
title ze chemat vyhazujeme a description tam taky nemame. takze tohle neni treba resit uz.

**Comment by killua-eu** [comment]
uzavřeme po sloučení všech json schémat na edit-new do jednoho a vyhození všech tech form titlu.
