### ISSUE TITLE
Remove duplicate schemas

### ISSUE THREAD

**Issue by killua-eu** [vaizard/glued#72]
Today I found in `controllers/accounting/v1/jsonschemas` two files:

- edit_bill_form.json
- new_bill_form.json

both are the same, only the title field differs. Kindly delete one, rename the other to 'cost.json'. Additionally:

- [ ] zkontroluj, ze tato duplikace neni jeste jinde, jde to naprosto proti smyslu schemat jako jedineho zdroje pravdy o tom, jak ma vypadat formular a jak se maji validovat data.

**Comment by pohadkar** [comment]
takhle duplikace je u vsech modulu ktere pouzivaji schemata

**Comment by pohadkar** [comment]
pro modul accounting to mam hotovo. zaviram ale tvorim nove issue pro dalsi moduly
