### ISSUE TITLE
Tabulka účetních skupin

### ISSUE THREAD

**Issue by killua-eu** [vaizard/glued#73]
Prosím založ `t_accounting_account_groups` tabulku:

- c_uid - rbac
- c_owner - rbac
- c_group - rbac
- c_unixperms - rbac
- c_definition_id - id definice, jedna definice se bude sestavat z vice ucetnich skupin
- c_definition_name - nazev definice
- c_group_number - cislo ucetni skupiny
- c_group_description - popis ucetni skupiny

czech_default skupina bude mít nasledující hodnoty

```
GNR GROUP DESCRIPTION
520 osobní náklady
520 osobní náklady - prac. smlouvy
520 osobní náklady - dpp
520 osobní náklady - autorské honoráře
520 osobní náklady - oon
550 dhm
550 dhm - software do 60tkč
550 dhm - hardware do 40tkč
502 energie
510 služby
518 služby - telefony, internet, poštovné, spoje
518 služby - nájemné
511 služby - opravy a údržba
512 služby - cestovní náklady
518 služby - inzerce, reklama, propagace
518 služby - úklid
518 služby - ostatní
```

**Comment by pohadkar** [comment]
--
-- Struktura tabulky `t_accounting_account_groups`
--

CREATE TABLE `t_accounting_account_groups` (
  `c_uid` int(11) NOT NULL,
  `c_owner` int(11) NOT NULL,
  `c_group` int(11) NOT NULL,
  `c_unixperms` int(11) NOT NULL DEFAULT '500',
  `c_definition_id` int(11) NOT NULL,
  `c_definition_name` varchar(100) NOT NULL,
  `c_group_number` varchar(20) NOT NULL,
  `c_group_description` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Vypisuji data pro tabulku `t_accounting_account_groups`
--

INSERT INTO `t_accounting_account_groups` (`c_uid`, `c_owner`, `c_group`, `c_unixperms`, `c_definition_id`, `c_definition_name`, `c_group_number`, `c_group_description`) VALUES
(1, 1, 2, 500, 1, 'czech_default', '520', 'osobní náklady'),
(2, 1, 2, 500, 1, 'czech_default', '520', 'osobní náklady - prac. smlouvy'),
(3, 1, 2, 500, 1, 'czech_default', '520', 'osobní náklady - dpp'),
(4, 1, 2, 500, 1, 'czech_default', '520', 'osobní náklady - autorské honoráře'),
(5, 1, 2, 500, 1, 'czech_default', '520', 'osobní náklady - oon'),
(6, 1, 2, 500, 1, 'czech_default', '550', 'dhm'),
(7, 1, 2, 500, 1, 'czech_default', '550', 'dhm - software do 60tkč'),
(8, 1, 2, 500, 1, 'czech_default', '550', 'dhm - hardware do 40tkč'),
(9, 1, 2, 500, 1, 'czech_default', '502', 'energie'),
(10, 1, 2, 500, 1, 'czech_default', '510', 'služby'),
(11, 1, 2, 500, 1, 'czech_default', '518', 'služby - telefony, internet, poštovné, spoje'),
(12, 1, 2, 500, 1, 'czech_default', '518', 'služby - nájemné'),
(13, 1, 2, 500, 1, 'czech_default', '511', 'služby - opravy a údržba'),
(14, 1, 2, 500, 1, 'czech_default', '512', 'služby - cestovní náklady'),
(15, 1, 2, 500, 1, 'czech_default', '518', 'služby - inzerce, reklama, propagace'),
(16, 1, 2, 500, 1, 'czech_default', '518', 'služby - úklid'),
(17, 1, 2, 500, 1, 'czech_default', '518', 'služby - ostatní');

--
-- Klíče pro exportované tabulky
--

--
-- Klíče pro tabulku `t_accounting_account_groups`
--
ALTER TABLE `t_accounting_account_groups`
  ADD PRIMARY KEY (`c_uid`);

--
-- AUTO_INCREMENT pro tabulky
--

--
-- AUTO_INCREMENT pro tabulku `t_accounting_account_groups`
--
ALTER TABLE `t_accounting_account_groups`
  MODIFY `c_uid` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=18;
