### ISSUE TITLE
Database mirgations

### ISSUE THREAD

**Issue by killua-eu** [vaizard/glued#80]
Glued (still) doesn't implement a database installation/schema update mechanism and definitely needs one. There are some options out there, but for php https://phinx.org/ looked best, even though its rather heavy on syntax. Using phinx will:

- bring simple from-the-scratch installation
- bring simple upgrade/downgrade path
- be possibly faster to use out-of-the-box then to write a custom tool
- enforce a workstyle, won't just rely on someone remembering to do a new sql revision
- allow us to have a simpler CI implementation
- allow us to easily compare the CI an DEV database (or CI against any older relase fwm) and find easier bugfixing someone forgets to use phinx.

Here also a video intro https://codecourse.com/watch/database-migrations-with-slim

**Comment by pohadkar** [comment]
vypada to, ze parser phinxu nerozumi alter table.
nebere prikazy jako

ALTER TABLE `t_facebook_tokens`
  ADD PRIMARY KEY (`c_id`);

a

ALTER TABLE `t_facebook_tokens`
  MODIFY `c_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

**Comment by pohadkar** [comment]
do instalacniho souboru db byly pridany jeste autoincrementy, ktere tam chybely.

**Comment by pohadkar** [comment]
novy migracni soubor se zaklada prikazem
vendor/bin/phinx create NoveUpravyMigrace
velke pismena v nazvu jsou dulezite, protoze se pak nazev prevadi na soubor podle pravidla
datum-nove-upravy-migrace

**Comment by pohadkar** [comment]
zalozil jsem novy migracni soubor, ktery do tabulky t_users pridava json sloupecek profile_data
je treba otestovat instalaci jestli se tam skutecne prida, a jestli bude mit default null hodnotu
