### ISSUE TITLE
Accounting>costs `.data.right_column.financial_acc[0] should be object`

### ISSUE THREAD

**Issue by killua-eu** [vaizard/glued#98]
`.data.right_column.financial_acc[0] should be object` error emitted when financial accounting empty but managerial accounting filled out. How to reproduce:

- Created a new cost (without managerial or fin. accounting)
- Add managerial accounting cost
- submit to see errror.

**Comment by pohadkar** [comment]
chvili mi to delalo u jednoho stareho zaznamu. ale kdyz jsem tam vypl a zapl to manageriel a financial, tak to delat prestalo. a u noveho se mi to nedari zreplikovat. muzes jeste podrobneji popsat ten postup jak to zreplikovat?

**Comment by pohadkar** [comment]
a odlis prosimte pripad kdy je zalozen aspon 1 item, ale nevyplnen. a kdy neni vubec zalozen.

**Comment by pohadkar** [comment]
chyba byla v tom, ze jsem data ze sloupcu prehazoval do korene jsonu pres asociativni pole. prazdny objekt to pak spatne prevedlo jako prazdne pole.

opraveno tak, ze polozky ze a do sloupcu presouvam primo jako objekty.
